#ifndef GRAPHIC_MESH_TYPES_IS_DEFINED
#define GRAPHIC_MESH_TYPES_IS_DEFINED

#define ASSIMP_BUILD_BOOST_WORKAROUND

#define ASSIMP_MESH_VERTEX	(D3DFVF_XYZ|D3DFVF_NORMAL|D3DFVF_DIFFUSE|D3DFVF_TEX1)

struct Assimp_Mesh_Vertex
{
	D3DXVECTOR3 Pos;
	D3DXVECTOR3 Normal;
	D3DCOLOR Diffuse;
	float tx, ty;
};
#endif