#ifndef GRAPHIC_CAMERA_TYPES_IS_DEFINED
#define GRAPHIC_CAMERA_TYPES_IS_DEFINED

#define MAXCAMROT_X				D3DX_PI/2.0f

#define STANDART_SPEED			20.0f
#define STANDART_SPEED_CAM		2.5f
#define STANDART_SPEED_ROT		100.0f
#define STANDART_SPEED_ROT_CAM	10.0f

#endif